import React from 'react';
import { ButtonWrapper, Wrapper } from './styles';
import { GenericButton } from '../../../ui/GenericButton';

interface Props {
  setChecked: () => void
}

export function Agreement ({ setChecked }: Props) {
  return <Wrapper>
    <div>
      I WOULD LIKE TO RECEIVE THE GAMIGO GROUP NEWSLETTER
      THIS IS THE NEWSLETTER OF THE GAMIGO GROUP (ALL COMPANIES INVOLVED CAN BE VIEWED HERE).
      I AGREE THAT EVERY COMPANY OF THE GAMIGO GROUP MAY INFORM ME ABOUT ALL OFFERS, SERVICES, AND OTHER ACTIVITIES,
      INCLUDING THOSE OF OTHER COMPANIES IN THE GROUP. FURTHER INFORMATION IS AVAILABLE IN THE PRIVACY POLICY.
      THIS AGREEMENT CAN BE WITHDRAWN AT ANY TIME AND WITHOUT STATING REASONS VIA THE UNSUBSCRIBE BUTTON.
      <br />
      <br />
      GAMIGO GROUP: AERIA GAMES GMBH (ADDRESS: SCHLESISCHE STR. 27C, 10997 BERLIN, GERMANY)
      GAMIGO US INC. (ADDRESS: 9430 RESEARCH BLVD, AUSTIN, TX 78759, UNITED STATES OF AMERICA)
      GAMIGO AG (ADDRESS: BEHRINGSTR. 16B, 22765 HAMBURG, GERMANY)
      GAMIGO INC. (ADDRESS: 800 BELLEVUE WAY NE, SUITE 500, BELLEVUE, WA 98004, UNITED STATES OF AMERICA)
      GAMIGO PUBLISHING GMBH (ADDRESS: BEHRINGSTR. 16B, 22765 HAMBURG, GERMANY)
      GAMIGO PORTALS GMBH (ADDRESS: BEHRINGSTR. 16B, 22765 HAMBURG, GERMANY)
    </div>
    <ButtonWrapper>
      <GenericButton onClick={setChecked}>Agree</GenericButton>
    </ButtonWrapper>
  </Wrapper>
}
